// demos/webpack5-vue3/src/components/inspector-demo/ShortcutPanel.vue
<template>
  <div class="inspector-shortcuts" aria-label="默认组合键">
    <div class="inspector-shortcut">
      <span>Mac</span>
      <kbd>Option</kbd>
      <kbd>Shift</kbd>
    </div>
    <div class="inspector-shortcut">
      <span>Windows</span>
      <kbd>Alt</kbd>
      <kbd>Shift</kbd>
    </div>
  </div>
</template>

// demos/mako/src/components/inspector-demo/ShortcutPanel.tsx
export function ShortcutPanel() {
  return (
    <div className="inspector-shortcuts" aria-label="默认组合键">
      <div className="inspector-shortcut">
        <span>Mac</span>
        <kbd>Option</kbd>+<kbd>Shift</kbd>
      </div>
      <div className="inspector-shortcut">
        <span>Windows</span>
        <kbd>Alt</kbd>+<kbd>Shift</kbd>
      </div>
    </div>
  );
}
