// demos/farm-vue3/src/App.vue
<script setup lang="ts">
import DemoHero from './components/inspector-demo/DemoHero.vue';
import ShortcutPanel from './components/inspector-demo/ShortcutPanel.vue';
import StepCards from './components/inspector-demo/StepCards.vue';
import TryTargets from './components/inspector-demo/TryTargets.vue';
</script>

<template>
  <main class="inspector-demo">
    <section class="inspector-shell" aria-labelledby="inspector-title">
      <DemoHero />
      <ShortcutPanel />
      <StepCards />
      <TryTargets />
    </section>
  </main>
</template>

// demos/vite-svelte/src/App.svelte
<script lang="ts">
  import DemoHero from './lib/inspector-demo/DemoHero.svelte'
  import ShortcutPanel from './lib/inspector-demo/ShortcutPanel.svelte'
  import StepCards from './lib/inspector-demo/StepCards.svelte'
  import TryTargets from './lib/inspector-demo/TryTargets.svelte'
</script>

<main class="inspector-demo">
  <section class="inspector-shell" aria-labelledby="inspector-title">
    <DemoHero />
    <ShortcutPanel />
    <StepCards />
    <TryTargets />
  </section>
</main>
