// demos/farm-vue3/src/components/inspector-demo/StepCards.vue
<template>
  <div class="inspector-grid">
    <article class="inspector-card">
      <span>01</span>
      <h2>Hold down the keys</h2>
      <p>Hold down the keys to make the plugin enter a inspection state.</p>
    </article>
    <article class="inspector-card">
      <span>02</span>
      <h2>Move the mouse</h2>
      <p>Move to any to view the element mask prompt.</p>
    </article>
    <article class="inspector-card">
      <span>03</span>
      <h2>Click the element</h2>
      <p>
        Clicking the element will automatically open the IDE and locate to the
        source code position.
      </p>
    </article>
  </div>
</template>

// demos/vite-svelte/src/lib/inspector-demo/StepCards.svelte
<div class="inspector-grid">
  <article class="inspector-card">
    <span>01</span>
    <h2>Hold down the keys</h2>
    <p>Hold down the keys to make the plugin enter a inspection state.</p>
  </article>
  <article class="inspector-card">
    <span>02</span>
    <h2>Move the mouse</h2>
    <p>Move to any  to view the element mask prompt.</p>
  </article>
  <article class="inspector-card">
    <span>03</span>
    <h2>Click the element</h2>
    <p>Clicking the element will automatically open the IDE and locate to the source code position.</p>
  </article>
</div>
