// demos/next15/app/components/inspector-demo/StepCards.tsx
export function StepCards() {
  return (
    <div className="inspector-grid">
      <article className="inspector-card">
        <span>01</span>
        <h2>Hold down the keys</h2>
        <p>Hold down the keys to make the plugin enter a inspection state.</p>
      </article>
      <article className="inspector-card">
        <span>02</span>
        <h2>Move the mouse</h2>
        <p>Move to any to view the element mask prompt.</p>
      </article>
      <article className="inspector-card">
        <span>03</span>
        <h2>Click the element</h2>
        <p>
          Clicking the element will automatically open the IDE and locate to the
          source code position.
        </p>
      </article>
    </div>
  );
}

// demos/farm-vue3/src/components/inspector-demo/StepCards.vue
<template>
  <div class="inspector-grid">
    <article class="inspector-card">
      <span>01</span>
      <h2>Hold down the keys</h2>
      <p>Hold down the keys to make the plugin enter a inspection state.</p>
    </article>
    <article class="inspector-card">
      <span>02</span>
      <h2>Move the mouse</h2>
      <p>Move to any to view the element mask prompt.</p>
    </article>
    <article class="inspector-card">
      <span>03</span>
      <h2>Click the element</h2>
      <p>
        Clicking the element will automatically open the IDE and locate to the
        source code position.
      </p>
    </article>
  </div>
</template>
