// demos/farm-vue3/src/App.vue
<script setup lang="ts">
import DemoHero from './components/inspector-demo/DemoHero.vue';
import ShortcutPanel from './components/inspector-demo/ShortcutPanel.vue';
import StepCards from './components/inspector-demo/StepCards.vue';
import TryTargets from './components/inspector-demo/TryTargets.vue';
</script>

<template>
  <main class="inspector-demo">
    <section class="inspector-shell" aria-labelledby="inspector-title">
      <DemoHero />
      <ShortcutPanel />
      <StepCards />
      <TryTargets />
    </section>
  </main>
</template>

// demos/webpack-react/src/App.tsx
import { DemoHero } from './components/inspector-demo/DemoHero';
import { ShortcutPanel } from './components/inspector-demo/ShortcutPanel';
import { StepCards } from './components/inspector-demo/StepCards';
import { TryTargets } from './components/inspector-demo/TryTargets';
import './App.css';

function App() {
  return (
    <main className="inspector-demo">
      <section className="inspector-shell" aria-labelledby="inspector-title">
        <DemoHero />
        <ShortcutPanel />
        <StepCards />
        <TryTargets />
      </section>
    </main>
  );
}

export default App;
