// demos/webpack-vue-tsx/src/components/inspector-demo/StepCards.vue
<template>
  <div class="inspector-grid">
    <article class="inspector-card">
      <span>01</span>
      <h2>按住组合键</h2>
      <p>保持按下组合键，让插件进入可检查状态。</p>
    </article>
    <article class="inspector-card">
      <span>02</span>
      <h2>移动鼠标</h2>
      <p>移动到标题、按钮、卡片等任意元素，查看页面遮罩提示。</p>
    </article>
    <article class="inspector-card">
      <span>03</span>
      <h2>点击元素</h2>
      <p>点击当前元素，IDE 会自动打开并跳到对应源码位置。</p>
    </article>
  </div>
</template>

// demos/webpack-react/src/components/inspector-demo/StepCards.tsx
export function StepCards() {
  return (
    <div className="inspector-grid">
      <article className="inspector-card">
        <span>01</span>
        <h2>按住组合键</h2>
        <p>保持按下组合键，让插件进入可检查状态。</p>
      </article>
      <article className="inspector-card">
        <span>02</span>
        <h2>移动鼠标</h2>
        <p>移动到标题、按钮、卡片等任意元素，查看页面遮罩提示。</p>
      </article>
      <article className="inspector-card">
        <span>03</span>
        <h2>点击元素</h2>
        <p>点击当前元素，IDE 会自动打开并跳到对应源码位置。</p>
      </article>
    </div>
  );
}
