// demos/vite-qwik/src/components/inspector-demo/DemoHero.tsx
import { component$ } from '@builder.io/qwik';

export const DemoHero = component$(() => {
  return (
    <div>
      <p class="inspector-badge">code-inspector-plugin demo</p>
      <div class="inspector-hero">
        <h1 id="inspector-title">Hold down the keys to locate code</h1>
        <p>
          Hold down the keys on the page and move the mouse, and the DOM element
          will display a positioning mask; click the element will open the
          IDE{' '}
        </p>
      </div>
    </div>
  );
});

// demos/vite-react/src/components/inspector-demo/DemoHero.tsx
export function DemoHero() {
  return (
    <div>
      <p className="inspector-badge">code-inspector-plugin demo</p>
      <div className="inspector-hero">
        <h1 id="inspector-title">Hold down the keys to locate code</h1>
        <p>
          Hold down the keys on the page and move the mouse, and the DOM element
          will display a positioning mask; click the element will open the IDE{' '}
        </p>
      </div>
    </div>
  );
}
